services:
  - type: web
    name: akin-world-web
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5000
      - key: AI_MUSIC_API_KEY
        sync: false
